/*
 * Stepper_prog.c
 *
 *  Created on: ???/???/????
 *      Author: abosh
 */

#include "../../LIBRARIES/BIT_MASK.h"
#include "../../LIBRARIES/errorStates.h"
#include "../../LIBRARIES/stdTypes.h"

#include "../../MCAL/DIO/DIO_int.h"
#include "../../MCAL/Timer0/TIMER0_int.h"
#include "../../MCAL/interrupt.h"

#include <util/delay.h>

#include "Stepper_config.h"
#include "Stepper_priv.h"


void Stepper_voidInit(){

	TIMER0_enuInit();
	DIO_enuSetPinDirection(STEPPER_PORT,STEPPER_PINA,DIO_u8OUTPUT);
	DIO_enuSetPinDirection(STEPPER_PORT,STEPPER_PINB,DIO_u8OUTPUT);
	DIO_enuSetPinDirection(STEPPER_PORT,STEPPER_PINC,DIO_u8OUTPUT);
	DIO_enuSetPinDirection(STEPPER_PORT,STEPPER_PIND,DIO_u8OUTPUT);

}

void Stepper_voidHalfStep(){
	u8 Local_u8Iterator;
		for(Local_u8Iterator= ZERO;Local_u8Iterator<STEPS;Local_u8Iterator++){

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);



		}

}

void Stepper_voidFullStep(){
	u8 Local_u8Iterator;
	for(Local_u8Iterator= ZERO;Local_u8Iterator<STEPS;Local_u8Iterator++){

		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8HIGH);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8HIGH);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
		TIMER0_enuSetDelay(DELAY);


		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8HIGH);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8HIGH);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
		TIMER0_enuSetDelay(DELAY);

		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8HIGH);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8HIGH);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
		TIMER0_enuSetDelay(DELAY);

		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8HIGH);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8HIGH);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
		TIMER0_enuSetDelay(DELAY);

		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8HIGH);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8HIGH);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
		DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
		TIMER0_enuSetDelay(DELAY);

	}

}

void Stepper_voidAntiClockwiseHalfStep(){

u8 Local_u8Iterator;
		for(Local_u8Iterator= ZERO;Local_u8Iterator<STEPS;Local_u8Iterator++){

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);


			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

		}

}

void Stepper_voidAntiClockwiseFullStep(){
	u8 Local_u8Iterator;
		for(Local_u8Iterator= ZERO;Local_u8Iterator<STEPS;Local_u8Iterator++){
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8HIGH);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);
			DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
			TIMER0_enuSetDelay(DELAY);

		}


}
void Stepper_voidStop(){
	DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINC,DIO_u8LOW);
	DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PIND,DIO_u8LOW);
	DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINA,DIO_u8LOW);
	DIO_enuSetPinValue(STEPPER_PORT,STEPPER_PINB,DIO_u8LOW);

}

